[package]
name = "xcat"
version = "0.2.0"
description = "终端 Markdown 预览工具"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
pulldown-cmark = "0.13.0"
ratatui = "0.30.0"
unicode-width = "0.2.2"
viuer = { version = "0.11.0", features = ["print-file"] }
